# Generated by Django 4.1.4 on 2022-12-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('technology', models.CharField(max_length=75, unique=True)),
                ('course', models.CharField(max_length=75, unique=True)),
                ('active', models.BooleanField()),
                ('completed', models.BooleanField()),
                ('certificate', models.BooleanField(verbose_name='Certificate Available')),
                ('cert_image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
