# Generated by Django 4.1.4 on 2022-12-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_alter_myeducation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myeducation',
            name='default_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
