# Generated by Django 4.1.4 on 2022-12-31 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_remove_myeducation_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myeducation',
            name='default_image',
        ),
    ]
