# Generated by Django 4.1.4 on 2022-12-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_remove_myeducation_default_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('details', models.TextField()),
            ],
        ),
    ]
