# Generated by Django 4.1.4 on 2022-12-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=75, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=75, null=True)),
                ('link', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('technology', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
