# Generated by Django 4.1.4 on 2022-12-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_myproject_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
