# Generated by Django 4.1.4 on 2023-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_myproject_github_url_myproject_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='myproject',
            name='link_url',
        ),
        migrations.AlterField(
            model_name='myproject',
            name='github',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='myproject',
            name='link',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
